each{Arg,Dir,File}: FIX: Combination of --with-header with --status-99-is-noop or --single-success not allowed (cp. 871732a)
> ERROR: Cannot combine runWith[Prompt] arguments with --with-header.

Need to parse those two flags into a separate commonArgs array, since they don't switch to the runWith backend.

(This relates to commit 871732a10f8635dd864af9f960fdddfeae3bcafe)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0